### ISSUE TITLE
Any plans for publishing release 1.10.1 in PyPi

### ISSUE THREAD

**Issue by amaltaro** [cern-fts/gfal2-python#2]
I see that the latest 1.10.x releases have a few extremely important bug fixes and I wonder if there are any plans to package and upload that version to PyPi? Thanks

**Comment by mpatrascoiu** [comment]
Hello,

We are very close to having the v1.11.0 release, which is the better candidate for PyPi.
We had no plans to publish to PyPi, however, if there is demand, I can dust off the publishing procedure.

Cheers,  
Mihai

**Comment by amaltaro** [comment]
@mpatrascoiu Hi Mihai, thanks for the prompt feedback. Yes, if it does not take too much effort on your side, it would be great to have 1.10.1 available in PyPi. 

This would help us having a more solid software stack, and hopefully it would also solve an unexpected segfault that we have been getting in a recently commissioned service. FYI @todor-ivanov

**Comment by todor-ivanov** [comment]
Thanks @mpatrascoiu and @amaltaro. That would indeed be very helpful for us. Please keep us posted.

**Comment by amaltaro** [comment]
@mpatrascoiu Mihai, just so I can organize the required activities on my side. Do you think you would be able to upload this version (or the newest one being developed) to PyPi this week? 
If not, then I will start considering a plan B, which is building this library ourselves. Preference is to use PyPi though.

**Comment by mpatrascoiu** [comment]
Hello,

We have released `gfal2-python v1.11.0` last week, and starting today, including on Pypi.

Please give it a go.

Cheers,  
Mihai
