### ISSUE TITLE
Install on Debian/Ubuntu

### ISSUE THREAD

**Issue by cfenell** [cern-fts/gfal2-python#4]
Dear all,
For your information, I have also encountered a few issues when installing on Debian/Ubuntu and here are my results so far.
I have written down some notes here:
https://github.com/cfenell/rucio-1/blob/install-doc/doc/gfal2.md
My notes on installing Rucio on Ubuntu are also here:
https://github.com/cfenell/rucio-1/blob/install-doc/doc/rucio-server.md

* Debian stable with gfal2 library and plugins from Debian unstable packages (version 2.20.5-1): gfal2-python and gfal2-util from develop branch compile without problems and the gfal CLI utils seem to work flawlessly.

* Ubuntu 20.04 with gfal2 version 2.20.3: gfal2-python and gfal2-util from develop branch fail to compile. Master branch compiles but I get
gfal-ls gsiftp://..../
gfal-ls error: 70 (Communication error on send) - globus_l_ftp_control_send_cmd_cb: gss_init_sec_context failed to generate output token  
Is this expected or have I missed something else?

Best regards Carl-Fredrik Enell, EISCAT

**Comment by mpatrascoiu** [comment]
Hello,

Thanks for reporting this!

It's definitely not expected, but at the same time, Debian and/or Ubuntu are not our main platforms so the result is not entirely surprising.

I went through the installation guide [1]. If I understand correctly, you've installed a tagged release of the `gfal2` library and later tried to compile `gfal2-python` from the `develop` branch. This wouldn't work as we're transitioning Gfal2 projects to the next major release series. This means the `develop` branches are on `gfal2-util-1.8.0` / `gfal2-python-1.12.0` / `gfal2-2.21.0`. Having `gfal2-python` from `develop` branch (`1.12.x` series) won't compile without `gfal2 2.21.x` series.

I would recommend to always build either the `develop` branch on all projects or the tagged release (`master` branch) on all projects. Mixing a `develop` branch with a tagged dependency won't work between major releases.

Can you try again having all of them compiled from `develop` branch or the latest tag?
(`gfal2-util-1.7.1` / `gfal2-python-1.11.1` / `gfal2-2.20.5`)

Cheers,
Mihai

[1] https://github.com/cfenell/rucio-1/blob/install-doc/doc/gfal2.md

**Comment by cfenell** [comment]
Hi, sorry for late reply! 
I have been trying to build gfal2 from source, but it fails due to missing dependencies, in spite of doing an
     apt-get build-dep gfal2 
(it finds no missing libraries).
Instead I use the gfal2 libraries and plugins from the Debian repositories. Debian unstable is at gfal2 version 2.20.5 and with this I could install gfal2-python and gfal2-utils successfully using the versions mentioned above. Master branch and tagged versions both worked.

So the problem is solved, I will update my installation guide!

**Comment by mpatrascoiu** [comment]
Hello,

Glad to hear it worked in the end.
I will close the ticket then.

Cheers,
Mihai
